# Generated by Django 5.0.6 on 2024-09-25 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0013_alter_pluginexecutionevent_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLinkStationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weatherlink_station_id', models.PositiveIntegerField(help_text='Select the WeatherLink Station ID', unique=True, verbose_name='WeatherLink Station ID')),
                ('last_imported', models.DateTimeField(blank=True, null=True, verbose_name='Last Imported')),
                ('station', models.OneToOneField(help_text='Station to link with ADCON', on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Station')),
            ],
            options={
                'verbose_name': 'WeatherLink Station Link',
                'verbose_name_plural': 'WeatherLink Stations Link',
            },
        ),
    ]
