# Generated by Django 5.0.6 on 2024-10-02 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_station_wmo_station_number'),
        ('wis2box_adl_weatherlink_v2_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlinkstationmapping',
            name='station',
            field=models.OneToOneField(help_text='Station to link', on_delete=django.db.models.deletion.CASCADE, to='core.station', verbose_name='Station'),
        ),
        migrations.CreateModel(
            name='WeatherLinkStationDataStructureMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_conditions_data_structure_type', models.PositiveIntegerField(blank=True, null=True)),
                ('station_mapping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wis2box_adl_weatherlink_v2_plugin.weatherlinkstationmapping', verbose_name='Station Mapping')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherLinkStationParameterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weatherlink_parameter', models.CharField(max_length=255, verbose_name='WeatherLink Parameter')),
                ('data_structure_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weatherlink_station_parameter_mappings', to='wis2box_adl_weatherlink_v2_plugin.weatherlinkstationdatastructuremapping', verbose_name='Station Mapping')),
                ('parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='Parameter')),
            ],
            options={
                'verbose_name': 'WeatherLink Station Parameter Mapping',
                'verbose_name_plural': 'WeatherLink Station Parameter Mapping',
            },
        ),
        migrations.AddConstraint(
            model_name='weatherlinkstationparametermapping',
            constraint=models.UniqueConstraint(fields=('data_structure_mapping', 'parameter'), name='unique_weatherlink_station_mapping_parameter'),
        ),
    ]
