# Generated by Django 5.0.6 on 2024-10-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2box_adl_weatherlink_v2_plugin', '0002_alter_weatherlinkstationmapping_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlinkstationdatastructuremapping',
            name='station_mapping',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_structure_mapping', to='wis2box_adl_weatherlink_v2_plugin.weatherlinkstationmapping', verbose_name='Station Mapping'),
        ),
    ]
