# Generated by Django 5.0.6 on 2024-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wis2box_adl_weatherlink_v2_plugin', '0003_alter_weatherlinkstationdatastructuremapping_station_mapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlinkstationdatastructuremapping',
            name='current_conditions_data_structure_type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
