# Generated by Django 5.0.6 on 2024-10-02 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_station_wmo_station_number'),
        ('wis2box_adl_weatherlink_v2_plugin', '0004_alter_weatherlinkstationdatastructuremapping_current_conditions_data_structure_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlinkstationparametermapping',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='Parameter'),
        ),
    ]
